version: '2.18.1'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile_apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - my-app-mysql

  my-app-mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
